### ISSUE TITLE
Library not being ignored.

### ISSUE THREAD

**Issue by valkyrienyanko** [eric78963/shroomJumper#4]
`[Li]brary` is in the `.gitignore` except it's not being ignored making your repo very large in file size to download. I don't think you need to commit the library folder iirc. I would suggest deleting it through GitHub.

**Comment by KaiHuaLin** [comment]
thanks for letting me know, I fixed the gitignore file, but how do I delete the Library folder on Github?

**Comment by valkyrienyanko** [comment]
You can use git CLI.

`git rm -r Library`
`git commit -m "Removed Library"`
`git push -u origin master`

**Comment by KaiHuaLin** [comment]
I think the problem has been fixed now, thank you!
